name: HDF5_BLS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest  # You can change this to 'windows-latest' or 'macos-latest'

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10] 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout the repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use the latest version of Python 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies listed in requirements.txt

    - name: Run tests with pytest
      run: |
        pip install pytest  # Ensure pytest is installed
        pytest  # Run the tests
